#!/bin/bash

#Constants
WAIT_TIME=1		# Wait 1 second between data collection

#Variables
CPUTEMP=O
CPUFREQ=0
VIDTEMP=0
MEMSTAT=0
CPUSTAT=0


# Collect stats Run until monitored process has terminated or stopped by user
counter=0
while ( true );
do
	(( counter++ ))

	#CPU Temperature
	CPUTEMP=$(cat </sys/class/thermal/thermal_zone0/temp)
	if ! mycmd; then
		echo "Could not get CPUTEMP"
		break
	fi

	#Frequency
	CPUFREQ=$(vcgencmd measure_clock core | awk 'BEGIN { FS = "=" } { printf "%.2f", $2/1000000 }' )
	if ! mycmd; then
		echo "Could not get CPUFREQ"
		break
	fi


	#Video tmp
	VIDTEMP=$(vcgencmd measure_temp | awk 'BEGIN { FS = "=" } { printf "%.2f", $2 }' )
	if ! mycmd; then
		echo "Could not get VIDTEMP"
		break
	fi


	#Memory
	MEMSTAT=$(free --giga | awk '(NR > 1)')
	if ! mycmd; then
		echo "Could not get MEMSTAT"
		break
	fi


	#CPU Usage
	CPUSTAT=$(mpstat -P ALL | awk '(NR > 3)')
	if ! mycmd; then
		echo "Could not get CPUSTAT"
		break
	fi


	# Write stats to current directory
 	FILENAME=$(printf "profile%08d")
	if ! mycmd; then
		echo "Could not generate filename $FILENAME"
		break
	fi

	printf "%s\n%s\n%s\n%s\n%s\n%s\n" "$counter" "$CPUTEMP" "$CPUFREQ" "$VIDTEMP" "$MEMSTAT" "$CPUSTAT" > "$FILENAME"
	if ! mycmd; then
		echo "Could not write file $FILENAME"
		break
	fi

	# Wait for next run
	sleep $WAIT_TIME
	if ! mycmd; then
		echo "Could not perform wait"
		break
	fi

done

	#handling signal
	trap handler
	handler
	{
		kill  SIGUSR1 "$PID"
	}


	#Parsing files  and generating graphs

	input='/home/john/CPT264---UNIX-Assignment-2/profile00000000'

	while IFS=$(read -r line);do
		echo "$line"
	done < "$input"


